### PR TITLE
Bluetooth LE Scanning for Gigaset G-tag

### PR DESCRIPTION
**Pull request by reddevil156**
Changed the bluetooth script to support Bluetooth LE scanning. Because the python-bluez[le] library did not work for me I changed to bluepy for this purpose.
It is primary used for scanning tags like the Gigaset G-tag. It detects the presence of the tag and reports if found or missing.

### CODE REVIEW

**Comment by reddevil156** [comment]
I see your point. I changed the script according to your proposal. 

Now anyone can use the script even if bluepy is not installed. If BTLE is selected in the ini file and bluepy is not installed an exception will be thrown and tells the user to install it.

Because I'm not very familiar I don't know how to update in this request. Do I have to close it and request a new pull or can I do this in an other way?

**Comment by rkoshak** [comment]
Great work. Thanks, for the contribution. Now that I look at it, we should probably do the same thing for pythonblues as well, unless bluepy depends on pythonblues. That way the bluepy BTLE users don't have to install pythonblues if they are not going to use it.

If you are willing to make that change please do so. If not, I'll merge this PR and open a new issue for this.

Thanks again!

**Comment by reddevil156** [comment]
Had an intend error in my bluetooth le scanning. It is now fixed and works again.

These were my first footsteps in python. I don't know if I find the time to get rid of this dependency. I think it's the best when you open a new issue and we will see ;)

**Comment by rkoshak** [comment]
If you are happy with the code I'll merge your changes. Thanks again for the PR!

**Comment by reddevil156** [comment]
Sorry for my late reply, was a little bit busy the last week.
Anyway I used the script in my home automation system and works really well. I think you can merge the changes.

**Pull request merged**
